### ISSUE TITLE
error repo에 커밋한 내용 완성하지 못한 부분 올립니다.

### ISSUE THREAD

**Issue by KJJDSA** [KJJDSA/MINIPROJECT_BACK#35]
지금 5시 43분이라 늦잠잘수도 있을 것 같아서 미리 말씀드리고자 올려드립니다. 

get --- star/posts?page= &pagesize= 부분인데, get 이미 만진 김에 요청한 user가 각 게시글에 좋아요를 했는지 안했는지를 구별할 수 있게 값을 추가로 넣어주면 좋을것 같다는 생각이 들어서 

로그인한 유저의 토큰을 받는 미들웨어를 작성해 붙였고, 받은 userId 를 사용해서 userLike: true(false) 를 각 posts에 붙여넣는것까지는 성공했습니다. 

근데 로그인 하지 않은 user들도 이 미들웨어를 통과하는데 이때  res.locals.user가 undefined가 되는 에러가 발생합니다. 이를 해결할 방법을 찾아보아야 할듯 합니다.

**Comment by JG-Jeong** [comment]
"근데 로그인 하지 않은 user들도 이 미들웨어를 통과하는데 이때 res.locals.user가 undefined가 되는 에러가 발생합니다. 이를 해결할 방법을 찾아보아야 할듯 합니다. " 에 대한 궁금증으로
-> FE분들과 같이 작업하신건가요? / auth-middleware.js의 14번째 줄에  authToken을 받아와야 하는데 코드 상에 7번째 줄의 authorization을 JWT토큰을 만드는 코드가 없습니다. 따라서 authoriztion 이 빈값일것 같은데... 이 부분은 https로 바꾸고, 코드를 cookie로 보내주면 해결될것 같습니다. 아마 다른 auth-middleware를 통과하는것들도 undefined일것 같은데 확인 해보시죠.
